#! /bin/sh

arg_c=$#
if test $arg_c -lt 1; then
  echo "Error: must specify memcpy@gcc version."
else
  ./configure --enable-cxx-shared-module=no --enable-cxx-shared-module=$1
  sed -i 's/archive_cmds="\\$CC -shared \\$libobjs \\$deplibs \\$compiler_flags \\${wl}-soname \\$wl\\$soname -o \\$lib"/archive_cmds="\\g++ -shared -static-libstdc++ -static-libgcc \\$libobjs \\$deplibs \\$compiler_flags \\${wl}-soname \\$wl\\$soname -o \\$lib"/' ./libtool
fi