version: 2.1
jobs:
  build:
    docker:
      - image: php:7.1.6-cli
    steps:
      - run:
          name: gxx version
          command: |
            g++ --version
      - checkout
      - run:
          name: Configure
          command: |
            phpize
            ./configure
      - run:
          name: Build
          command: |
            make
      - run:
          name: Test
          command: |
            make test
            